[project]
name = "archmage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "smolagents[litellm]>=1.14.0",
    "sqlite-vec>=0.1.6",
]
