[project]
name = "archmage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "peewee>=3.17.9",
    "smolagents[litellm]>=1.14.0",
]
